"""
Coordinator gRPC server.

Implements the FederatedLearning servicer defined in federated.proto.
Runs the aggregation event loop in a dedicated background thread to avoid
blocking the gRPC thread pool.

Streaming protocol
------------------
• FetchGlobalModel  — server-side streaming: the global model is split into
  chunk_size_bytes chunks and streamed to the requesting node.
• SendLocalUpdate   — client-side streaming: the node streams chunks; the
  server reassembles them before passing the full payload to the registry.

Privacy middleware is applied at the boundary:
  • outbound (broadcast): apply_privacy_transform(payload) before chunking.
  • inbound  (update)   : reverse_privacy_transform(payload) after reassembly.
"""

from __future__ import annotations

import math
import os
import threading
import time
import uuid
from concurrent import futures
from typing import Iterator, Optional

import torch
import grpc

from fedsys.config import CoordinatorConfig, ModelConfig
from fedsys.coordinator.aggregator import (
    FedAvgAggregator,
    build_aggregator,
    serialize_state_dict,
)
from fedsys.coordinator.evaluator import evaluate, evaluate_ranking
from fedsys.coordinator.registry import NodeRegistry
from fedsys.interceptors import TelemetryServerInterceptor
from fedsys.logging_async import AsyncTelemetryLogger, TimedBlock
from fedsys.models.recommendation import build_model
from fedsys.privacy import apply_privacy_transform, reverse_privacy_transform

# Import generated gRPC stubs (generated by scripts/generate_proto.py)
from fedsys.generated import federated_pb2, federated_pb2_grpc


class FederatedLearningServicer(federated_pb2_grpc.FederatedLearningServicer):
    """
    gRPC servicer for the coordinator.

    All RPC methods are called from the gRPC thread pool.  Long-running work
    (waiting for K updates, running FedAvg) executes in the aggregation thread.
    """

    def __init__(
        self,
        cfg: CoordinatorConfig,
        model_cfg: ModelConfig,
        registry: NodeRegistry,
        aggregator: FedAvgAggregator,
        logger: AsyncTelemetryLogger,
    ) -> None:
        self._cfg = cfg
        self._registry = registry
        self._aggregator = aggregator
        self._logger = logger

        # Global model state — updated after each aggregation round
        self._model_lock = threading.RLock()
        self._global_model = build_model(model_cfg)
        self._global_model_bytes: Optional[bytes] = None
        self._broadcast_epoch: int = 0

        # Condition the node threads wait on to receive the next global model
        self._model_ready = threading.Condition()

        self._init_global_model()

    # ------------------------------------------------------------------
    # Initialisation
    # ------------------------------------------------------------------

    def _init_global_model(self) -> None:
        """Serialize the initial random global model."""
        with self._model_lock:
            payload, ser_ms = serialize_state_dict(self._global_model.state_dict())
            self._global_model_bytes = payload
            self._logger.log({
                "event": "GLOBAL_MODEL_INIT",
                "param_count": sum(p.numel() for p in self._global_model.parameters()),
                "bytes": len(payload),
                "serde_ms": round(ser_ms, 4),
            })

    def update_global_model(self, state_dict: dict, epoch: int) -> None:
        """Called by the aggregation thread after FedAvg completes."""
        with self._model_lock:
            self._global_model.load_state_dict(state_dict)
            payload, _ = serialize_state_dict(state_dict)
            self._global_model_bytes = payload
            self._broadcast_epoch = epoch

        with self._model_ready:
            self._model_ready.notify_all()

    # ------------------------------------------------------------------
    # RPC: Register
    # ------------------------------------------------------------------

    def Register(
        self,
        request: federated_pb2.NodeInfo,
        context: grpc.ServicerContext,
    ) -> federated_pb2.RegistrationResponse:
        record = self._registry.register(
            node_id=request.node_id,
            address=request.address,
            local_dataset_size=request.local_dataset_size,
            metadata=dict(request.metadata),
        )
        self._logger.log({
            "event": "NODE_REGISTERED",
            "node_id": record.node_id,
            "partition": record.partition,
            "dataset_size": record.local_dataset_size,
            "total_registered": self._registry.registered_count,
        })
        return federated_pb2.RegistrationResponse(
            accepted=True,
            message=f"Registered as partition {record.partition}/{self._cfg.total_nodes}",
            assigned_partition=record.partition,
            total_partitions=self._cfg.total_nodes,
            confirmed_node_id=record.node_id,
        )

    # ------------------------------------------------------------------
    # RPC: FetchGlobalModel (server-side streaming)
    # ------------------------------------------------------------------

    def FetchGlobalModel(
        self,
        request: federated_pb2.EpochRequest,
        context: grpc.ServicerContext,
    ) -> Iterator[federated_pb2.ModelChunk]:
        node_id = request.node_id
        requested_epoch = request.epoch

        # Block until the coordinator has the model ready for this epoch
        with self._model_ready:
            while self._broadcast_epoch < requested_epoch:
                self._model_ready.wait(timeout=5.0)
                if not context.is_active():
                    return

        with self._model_lock:
            raw_payload = self._global_model_bytes
            epoch_id = str(uuid.uuid4())

        t_transform = time.perf_counter()
        payload = apply_privacy_transform(raw_payload, context=f"broadcast->{node_id}")
        transform_ms = (time.perf_counter() - t_transform) * 1_000

        chunk_size = self._cfg.chunk_size_bytes
        total_bytes = len(payload)
        total_chunks = math.ceil(total_bytes / chunk_size)

        self._logger.log({
            "event": "FETCH_MODEL_START",
            "node_id": node_id,
            "epoch": requested_epoch,
            "total_bytes": total_bytes,
            "total_chunks": total_chunks,
            "privacy_transform_ms": round(transform_ms, 4),
        })

        t_stream_start = time.perf_counter()
        for i in range(total_chunks):
            if not context.is_active():
                break
            start = i * chunk_size
            end = min(start + chunk_size, total_bytes)
            yield federated_pb2.ModelChunk(
                payload=payload[start:end],
                chunk_index=i,
                total_chunks=total_chunks,
                epoch_id=epoch_id,
                total_bytes=total_bytes,
            )

        stream_ms = (time.perf_counter() - t_stream_start) * 1_000
        self._logger.log({
            "event": "FETCH_MODEL_END",
            "node_id": node_id,
            "epoch": requested_epoch,
            "stream_ms": round(stream_ms, 4),
        })

    # ------------------------------------------------------------------
    # RPC: SendLocalUpdate (client-side streaming)
    # ------------------------------------------------------------------

    def SendLocalUpdate(
        self,
        request_iterator: Iterator[federated_pb2.ModelChunk],
        context: grpc.ServicerContext,
    ) -> federated_pb2.Ack:
        chunks: list[bytes] = []
        total_chunks = 0
        epoch_id = ""
        node_id = "unknown"
        expected_bytes = 0

        t_recv_start = time.perf_counter()

        for chunk in request_iterator:
            if not chunks:
                total_chunks = chunk.total_chunks
                epoch_id = chunk.epoch_id
                expected_bytes = chunk.total_bytes
                node_id = chunk.metadata.get("node_id", "unknown")
                self._logger.log({
                    "event": "UPDATE_RECV_START",
                    "node_id": node_id,
                    "epoch_id": epoch_id,
                    "expected_bytes": expected_bytes,
                    "total_chunks": total_chunks,
                })
            chunks.append(chunk.payload)

        recv_ms = (time.perf_counter() - t_recv_start) * 1_000
        raw_payload = b"".join(chunks)
        actual_bytes = len(raw_payload)

        self._logger.log({
            "event": "UPDATE_RECV_END",
            "node_id": node_id,
            "epoch_id": epoch_id,
            "actual_bytes": actual_bytes,
            "recv_ms": round(recv_ms, 4),
        })

        # Reverse privacy transform before handing bytes to the registry
        t_transform = time.perf_counter()
        payload = reverse_privacy_transform(raw_payload, context=f"{node_id}->coordinator")
        transform_ms = (time.perf_counter() - t_transform) * 1_000

        # Determine epoch from the chunk metadata (node must include it)
        epoch = int(chunk.metadata.get("epoch", self._registry.current_epoch))
        num_samples = int(chunk.metadata.get("num_samples", 1))

        accepted = self._registry.submit_update(
            node_id=node_id,
            epoch=epoch,
            payload_bytes=payload,
            num_samples=num_samples,
        )

        self._logger.log({
            "event": "UPDATE_SUBMITTED",
            "node_id": node_id,
            "epoch": epoch,
            "accepted": accepted,
            "privacy_transform_ms": round(transform_ms, 4),
            "pending_count": self._registry.pending_update_count(),
        })

        return federated_pb2.Ack(
            success=accepted,
            message="accepted" if accepted else "rejected (stale or unknown node)",
            node_id=node_id,
            epoch=epoch,
        )


# ---------------------------------------------------------------------------
# Checkpoint saving
# ---------------------------------------------------------------------------

def save_checkpoint(
    state_dict: dict,
    checkpoint_dir: str,
    epoch: int,
    logger: AsyncTelemetryLogger,
    val_metrics: Optional[dict] = None,
    is_best: bool = False,
    is_final: bool = False,
) -> str:
    """
    Save a model state dict to disk.

    Files written
    -------------
    checkpoints/model_epoch_{N}.pt  — after every completed round
    checkpoints/model_best.pt       — overwritten whenever val loss improves
    checkpoints/model_final.pt      — overwritten at the very last round

    Parameters
    ----------
    state_dict     : aggregated model weights (CPU tensors)
    checkpoint_dir : directory to write into (created if missing)
    epoch          : FL round that just completed
    logger         : async telemetry sink
    val_metrics    : dict of validation metrics to embed in the checkpoint
    is_best        : if True, also overwrite model_best.pt
    is_final       : if True, also overwrite model_final.pt

    Returns the path of the per-epoch file.
    """
    if not checkpoint_dir:
        return ""

    os.makedirs(checkpoint_dir, exist_ok=True)

    payload = {
        "epoch":            epoch,
        "model_state_dict": state_dict,
        "val_metrics":      val_metrics or {},
    }

    # Per-epoch checkpoint
    epoch_path = os.path.join(checkpoint_dir, f"model_epoch_{epoch}.pt")
    t0 = time.perf_counter()
    torch.save(payload, epoch_path)
    save_ms = (time.perf_counter() - t0) * 1_000

    logger.log({
        "event":   "CHECKPOINT_SAVED",
        "epoch":   epoch,
        "path":    epoch_path,
        "save_ms": round(save_ms, 4),
    })
    print(f"[coordinator] Checkpoint  -> {epoch_path}  ({save_ms:.1f} ms)")

    if is_best:
        best_path = os.path.join(checkpoint_dir, "model_best.pt")
        torch.save(payload, best_path)
        logger.log({"event": "CHECKPOINT_BEST_SAVED", "epoch": epoch, "path": best_path,
                    **(val_metrics or {})})
        # Print whichever metrics are available (BPR ranking or BCE pointwise)
        metrics_str = "  ".join(
            f"{k}={v:.4f}" for k, v in sorted((val_metrics or {}).items())
            if isinstance(v, float)
        )
        print(f"[coordinator] Best model  -> {best_path}  ({metrics_str})")

    if is_final:
        final_path = os.path.join(checkpoint_dir, "model_final.pt")
        torch.save(payload, final_path)
        logger.log({"event": "CHECKPOINT_FINAL_SAVED", "epoch": epoch, "path": final_path})
        print(f"[coordinator] Final model -> {final_path}")

    return epoch_path


# ---------------------------------------------------------------------------
# Aggregation loop (runs in a background thread)
# ---------------------------------------------------------------------------

def run_aggregation_loop(
    servicer: FederatedLearningServicer,
    registry: NodeRegistry,
    aggregator,
    logger: AsyncTelemetryLogger,
    num_rounds: int,
    min_nodes: int,
    checkpoint_dir: str = "checkpoints",
    val_loader=None,
    test_loader=None,
    ml_dataset=None,
    adv_target_item: int = -1,
    adv_target_genre: str = "",
) -> None:
    """
    Background thread: waits for K updates, aggregates, evaluates, checkpoints.

    Evaluation modes
    ----------------
    ml_dataset is not None  ->  ranking eval (Hit@K, NDCG@K); best = highest Hit@10
    val_loader is not None  ->  pointwise eval (BCE, acc, AUC); best = lowest val_loss

    Adversarial evaluation
    ----------------------
    When adv_target_item >= 0 and ml_dataset is provided, also runs
    target-exposure evaluation (target_hit@K, target_ndcg@K) after each round.
    """
    best_is_higher = ml_dataset is not None
    best_val_metric = -float("inf") if best_is_higher else float("inf")

    def _is_better(v: float) -> bool:
        return v > best_val_metric if best_is_higher else v < best_val_metric

    def _primary(m: dict) -> float:
        return m.get("hit@10", 0.0) if best_is_higher else m.get("loss", float("inf"))

    _run_adv_eval = (
        adv_target_item >= 0
        and bool(adv_target_genre)
        and ml_dataset is not None
    )

    for epoch in range(num_rounds):
        logger.log({"event": "ROUND_START", "epoch": epoch, "waiting_for": min_nodes})

        updates, sample_counts = registry.wait_for_updates()

        if not updates:
            logger.log({"event": "ROUND_TIMEOUT_NO_UPDATES", "epoch": epoch})
            registry.advance_epoch()
            continue

        logger.log({"event": "ROUND_UPDATES_READY", "epoch": epoch,
                    "num_updates": len(updates)})

        # Aggregation — pass global_state for robust defense methods
        with TimedBlock(logger, "FEDAVG", epoch=epoch):
            global_state = dict(servicer._global_model.state_dict())
            # RobustAggregator.aggregate accepts global_state kwarg;
            # FedAvgAggregator.aggregate ignores extra kwargs gracefully
            try:
                new_state, _ = aggregator.aggregate(
                    updates, sample_counts, epoch,
                    global_state=global_state,
                )
            except TypeError:
                # FedAvgAggregator doesn't accept global_state
                new_state, _ = aggregator.aggregate(updates, sample_counts, epoch)

        servicer._global_model.load_state_dict(new_state)

        # Validation
        val_metrics: Optional[dict] = None
        is_best = False

        if ml_dataset is not None:
            val_metrics = evaluate_ranking(
                servicer._global_model, ml_dataset,
                split="val", logger=logger, epoch=epoch,
            )
            parts = "  ".join(
                f"hit@{k}={val_metrics.get(f'hit@{k}', 0):.4f}  "
                f"ndcg@{k}={val_metrics.get(f'ndcg@{k}', 0):.4f}"
                for k in (10, 20) if f"hit@{k}" in val_metrics
            )
            print(f"[coordinator] Epoch {epoch:>3}  {parts}")
        elif val_loader is not None:
            val_metrics = evaluate(
                servicer._global_model, val_loader,
                logger=logger, split="val", epoch=epoch,
            )
            print(
                f"[coordinator] Epoch {epoch:>3}  "
                f"val_loss={val_metrics['loss']:.4f}  "
                f"val_acc={val_metrics['accuracy']:.4f}  "
                f"val_auc={val_metrics['auc_roc']:.4f}"
            )

        if val_metrics is not None and _is_better(_primary(val_metrics)):
            best_val_metric = _primary(val_metrics)
            is_best = True

        # ── Adversarial evaluation (target exposure) ──────────────────────
        if _run_adv_eval:
            from fedsys.adversarial.eval import evaluate_with_target_exposure
            adv_metrics = evaluate_with_target_exposure(
                model=servicer._global_model,
                dataset=ml_dataset,
                target_item_index=adv_target_item,
                target_genre=adv_target_genre,
                split="val",
                logger=logger,
                epoch=epoch,
            )
            tgt_h10 = adv_metrics.get("target_hit@10", 0.0)
            tgt_n10 = adv_metrics.get("target_ndcg@10", 0.0)
            print(
                f"[coordinator] Adv epoch {epoch:>3}  "
                f"target_hit@10={tgt_h10:.4f}  "
                f"target_ndcg@10={tgt_n10:.4f}"
            )

        is_final = (epoch == num_rounds - 1)
        save_checkpoint(
            new_state, checkpoint_dir, epoch, logger,
            val_metrics=val_metrics, is_best=is_best, is_final=is_final,
        )

        servicer.update_global_model(new_state, epoch + 1)
        registry.advance_epoch()
        logger.log({"event": "ROUND_END", "epoch": epoch})

    logger.log({"event": "ALL_ROUNDS_COMPLETE", "total_rounds": num_rounds})

    # Final test evaluation
    if ml_dataset is not None:
        test_metrics = evaluate_ranking(
            servicer._global_model, ml_dataset,
            split="test", logger=logger, epoch=num_rounds - 1,
        )
        lines = "\n".join(f"  {k}: {v}" for k, v in sorted(test_metrics.items()))
        print(f"\n[coordinator] ===== TEST SET (BPR RANKING) =====\n{lines}"
              f"\n[coordinator] ==================================")

        # Adversarial test-set target exposure
        if _run_adv_eval:
            from fedsys.adversarial.eval import evaluate_with_target_exposure
            adv_test = evaluate_with_target_exposure(
                model=servicer._global_model,
                dataset=ml_dataset,
                target_item_index=adv_target_item,
                target_genre=adv_target_genre,
                split="test",
                logger=logger,
                epoch=num_rounds - 1,
            )
            adv_lines = "\n".join(
                f"  {k}: {v:.6f}" for k, v in sorted(adv_test.items())
            )
            print(
                f"\n[coordinator] ===== TEST SET (ADVERSARIAL) =====\n{adv_lines}"
                f"\n[coordinator] ======================================"
            )
    elif test_loader is not None:
        test_metrics = evaluate(
            servicer._global_model, test_loader,
            logger=logger, split="test", epoch=num_rounds - 1,
        )
        print(
            f"\n[coordinator] ===== TEST SET RESULTS =====\n"
            f"  loss     : {test_metrics['loss']:.6f}\n"
            f"  accuracy : {test_metrics['accuracy']:.4f} "
            f"({test_metrics['accuracy']*100:.2f}%)\n"
            f"  AUC-ROC  : {test_metrics['auc_roc']:.4f}\n"
            f"[coordinator] ==============================="
        )


# ---------------------------------------------------------------------------
# Server entry point
# ---------------------------------------------------------------------------

def serve(cfg: CoordinatorConfig, model_cfg: ModelConfig) -> None:
    """Start the coordinator gRPC server and block until all rounds complete."""
    from fedsys.config import ensure_log_dir
    from fedsys.data.synthetic_dataset import load_csv_dataloader
    ensure_log_dir(cfg)

    logger = AsyncTelemetryLogger(cfg.log_file, cfg.db_path).start()

    registry = NodeRegistry(
        total_nodes=cfg.total_nodes,
        min_nodes=cfg.min_nodes,
        round_timeout=cfg.round_timeout_seconds,
    )
    aggregator = build_aggregator(
        logger=logger,
        defense_method=cfg.defense_method,
        clip_threshold=cfg.defense_clip_thresh,
        trim_fraction=cfg.defense_trim_frac,
        focus_k_frac=cfg.defense_focus_k_frac,
    )

    servicer = FederatedLearningServicer(
        cfg=cfg,
        model_cfg=model_cfg,
        registry=registry,
        aggregator=aggregator,
        logger=logger,
    )

    interceptor = TelemetryServerInterceptor(logger)
    server = grpc.server(
        futures.ThreadPoolExecutor(max_workers=cfg.total_nodes + 4),
        interceptors=[interceptor],
        options=cfg.grpc_options,
    )
    federated_pb2_grpc.add_FederatedLearningServicer_to_server(servicer, server)
    server.add_insecure_port(f"{cfg.host}:{cfg.port}")
    server.start()

    logger.log({
        "event": "SERVER_START",
        "address": f"{cfg.host}:{cfg.port}",
        "total_nodes": cfg.total_nodes,
        "min_nodes": cfg.min_nodes,
        "num_rounds": cfg.num_rounds,
        "defense_method": cfg.defense_method,
    })
    print(f"[coordinator] Listening on {cfg.host}:{cfg.port}  "
          f"(K={cfg.min_nodes} / N={cfg.total_nodes}  "
          f"defense={cfg.defense_method})")

    # ── Load evaluation data ──────────────────────────────────────────────
    val_loader  = None
    test_loader = None
    ml_dataset  = None

    if cfg.ml_data_root:
        # MovieLens ranking evaluation
        from fedsys.data.movielens_dataset import load_movielens_dataset
        print(f"[coordinator] Loading MovieLens ({cfg.ml_variant}) from {cfg.ml_data_root} ...")
        ml_dataset = load_movielens_dataset(
            cfg.ml_data_root, cfg.ml_variant, show_progress=True
        )
    else:
        # CSV-based pointwise evaluation (synthetic data)
        eval_batch = 256
        if cfg.val_data_path:
            print(f"[coordinator] Loading validation set from {cfg.val_data_path}")
            val_loader = load_csv_dataloader(cfg.val_data_path, batch_size=eval_batch)
        if cfg.test_data_path:
            print(f"[coordinator] Loading test set       from {cfg.test_data_path}")
            test_loader = load_csv_dataloader(cfg.test_data_path, batch_size=eval_batch)

    # ── Start aggregation loop ────────────────────────────────────────────
    agg_thread = threading.Thread(
        target=run_aggregation_loop,
        args=(servicer, registry, aggregator, logger,
              cfg.num_rounds, cfg.min_nodes, cfg.checkpoint_dir,
              val_loader, test_loader, ml_dataset),
        kwargs={
            "adv_target_item":  cfg.adv_target_item,
            "adv_target_genre": cfg.adv_target_genre,
        },
        name="aggregation-loop",
        daemon=False,
    )
    agg_thread.start()

    agg_thread.join()
    server.stop(grace=10)
    logger.stop()
    print("[coordinator] All rounds complete. Shutting down.")
